name: e_learning
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'
dependencies:
  cloud_firestore: ^4.13.6
  flutter_native_splash: ^2.3.2
  connectivity_plus: ^5.0.2
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  equatable: ^2.0.5
  firebase_auth: ^4.15.2
  firebase_core: ^2.24.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_spinkit: ^5.2.0
  get_it: ^7.6.4
  google_sign_in: ^6.1.6
  hexcolor: ^3.0.1
  intl: ^0.18.1
  shared_preferences: ^2.2.2
  video_player: ^2.8.1
  youtube_player_flutter: ^8.1.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.jpg"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/app_icon.jpg"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/app_icon.jpg"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/app_icon.jpg"
flutter:

  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-ExtraBold.ttf
          weight: 800
flutter_intl:
  enabled: true
